# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['gui_app.py'],
    pathex=[],
    binaries=[],
    datas=[
        # Mapping data files
        ('mapping\\circuits.json', 'mapping'),
        ('mapping\\teams.f1.json', 'mapping'),
        ('mapping\\lineups.f1.json', 'mapping'),
        ('mapping\\championships.json', 'mapping'),
        ('mapping\\drivers.json', 'mapping'),
        ('mapping\\nations.json', 'mapping'),
        ('mapping\\driver_alias_map.json', 'mapping'),
        ('mapping\\nations_alias_map.json', 'mapping'),
        ('mapping\\team_alias_map.json', 'mapping'),
        ('mapping\\cars.f1.json', 'mapping'),
        # Config files
        ('config.json', '.'),
        ('VERSION', '.'),
        ('icon.ico', '.'),
    ],
    hiddenimports=[
        'fastf1.events',
        'fastf1.api',
        'fastf1.core',
        'fastf1.ergast',
        'fastf1.mvapi',
        'fastf1.livetiming',
        'pandas',
        'numpy',
        'requests',
        'api.export_service',
        'api.providers.router',
        'api.providers.fastf1_provider',
        'api.providers.jolpica_provider',
        'api.providers.jolpica_api',
        'api.providers.base',
        'api.providers.aggregate',
        'api.data_mapper',
        'api.jolpica_api',
        'export.rlt_adapter',
        'export.rlt_enums',
        'mapping.drivers_aliases',
        'mapping.teams_aliases',
        'mapping.drivers_nations',
        'mapping.circuit_aliases',
        'mapping.normalize',
        'utils.logging_setup',
        'utils.config_loader',
        'core.version',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='LooneyF1Tool',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='LooneyF1Tool_1.7.2_beta',
)
